Fitvely/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from Fitvely import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("shopmember/", include("shopmember.urls")),
    path("shopnotice/", include("shopnotice.urls")),
    path("shopqna/", include("shopqna.urls")),
    path("shopproduct/", include("shopproduct.urls")),
    path("shopcart/", include("shopcart.urls")),
    path("shopreview/", include("shopreview.urls")),
    path("shoppay/", include(("shoppay.urls","pay"), namespace="pay")),
    path("shopreturn/", include("shopreturn.urls")),
    path('search/', include('search_product.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopcart/urls.py
from django.urls.conf import path
from shopcart import views

app_name="prodcart"
urlpatterns = [
    path("prodcart", views.Prodcart.as_view(), name="prodcart"),
    path("cartdelete", views.Cartdelete.as_view(), name="cartdelete"),
    path("basecartdelete", views.Baseartdelete.as_view(), name="basecartdelete"),
    path("cartupdate", views.Cartupdate.as_view(), name="cartupdate"),
    path("cartpaydetail", views.Cartpaydetail.as_view(), name="cartpaydetail"),
    path("cartpaydelete", views.Cartpaydelete.as_view(), name="cartpaydelete"),
    path("cartpaydeleteall", views.Cartpaydeleteall.as_view(), name="cartpaydeleteall"),
    ]

shopmember/urls.py
from django.urls.conf import path
from shopmember import views

app_name="member"

urlpatterns = [
        path("index", views.Index.as_view(), name="index"),
        path("signup", views.MemberSignup.as_view(), name="signup"),
        path("login", views.MemberLogin.as_view(), name="login"),
        path("confirm", views.MemberConfirm.as_view(),name="confirm"),
        path("logout", views.MemberLogout.as_view(),name="logout"),
        path("delete", views.MemberDelete.as_view(),name="delete"),
        path("modify", views.MemberModify.as_view(),name="modify"),
        path("modifypro", views.MemberModifypro.as_view(),name="modifypro"),
        path("mypage", views.Membermypage.as_view(),name="mypage"),     
        path("pappap", views.Fitpapup.as_view(),name="pappap"),
        path("myreview", views.Myreview.as_view(), name="myreview"),
    ] 

shopqna/urls.py
from django.urls.conf import path
from shopqna import views

app_name="qnaboard"

urlpatterns = [
    path("qnalist", views.Qnalist.as_view(), name="qnalist"),
    path("qnawrtie", views.Qnawrite.as_view(), name="qnawrite"),
    path("qnacontent", views.Qnacontent.as_view(), name="qnacontent"),
    path("qnadelete", views.Qnadelete.as_view(), name="qnadelete"),
    path("qnamodify", views.Qnamodify.as_view(), name="qnamodify"),
    path("qnamodifypro", views.Qnamodifypro.as_view(), name="qnamodifypro"),
    path("myqna", views.Myqna.as_view(), name="myqna"),
    ]

shopreturn/urls.py
from django.urls.conf import path
from shopreturn import views

app_name="return"
urlpatterns = [
        path("returnlist",views.Returnlist.as_view(),name="returnlist"),
        path("returncontent",views.Returncontent.as_view(), name="returncontent"),
        path("returndelete",views.Returndelete.as_view(), name="returndelete"),
        path("returnmodify",views.Returnmodify.as_view(), name="returnmodify"),
        path("returnmodifypro",views.Returnmodifypro.as_view(), name="returnmodifypro"),
        path("returnwrite", views.Returnwrite.as_view(), name="returnwrite"),   
        ]

shopmember/models.py
from django.db import models
from shopmember.choices import GENDER_CHOICE
from shopproduct.models import Shopproduct

# Create your models here.
class Shopmember(models.Model):
    user_id = models.CharField(max_length=100, verbose_name="아이디", primary_key=True)
    user_passwd = models.CharField(max_length=100, verbose_name="비밀번호", null=False)
    user_name = models.CharField(max_length=100, verbose_name="이름", null=False)
    user_tel = models.CharField(max_length=30, verbose_name="전화번호", null=False)
    user_email = models.CharField(max_length=100, verbose_name="이메일", null=False, default='')
    user_addr = models.CharField(max_length=1000, verbose_name="주소", null=False)
    user_addrt = models.CharField(max_length=1000, verbose_name="상세 주소", null=False)
    user_gender = models.CharField(choices=GENDER_CHOICE, max_length=100, verbose_name="성별", null=False)
    user_brand = models.CharField(max_length=100, verbose_name="선호 브렌드", null=True)
    
class Shopmemberdelete(models.Model):
    user_id = models.CharField(max_length=100, verbose_name="아이디")
    user_passwd = models.CharField(max_length=100, verbose_name="비밀번호", null=False)
    user_name = models.CharField(max_length=100, verbose_name="이름", null=False)
    user_tel = models.CharField(max_length=30, verbose_name="전화번호", null=False)
    user_email = models.CharField(max_length=100, verbose_name="이메일", null=False, default='')
    user_addr = models.CharField(max_length=1000, verbose_name="주소", null=False)
    user_addrt = models.CharField(max_length=1000, verbose_name="상세 주소", null=False)
    user_gender = models.CharField(choices=GENDER_CHOICE, max_length=100, verbose_name="성별", null=False)
    user_brand = models.CharField(max_length=100, verbose_name="선호 브렌드", null=True)
    
class Shoprecome(models.Model):
    prodnum = models.ForeignKey(Shopproduct, verbose_name = "상품번호", on_delete=models.CASCADE, db_column="prodnum")

shopmember/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.template import loader
from django.http.response import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from shopmember.models import Shopmember, Shopmemberdelete, Shoprecome
from django.core.exceptions import ObjectDoesNotExist
from shopcart.models import Shopcart
from shoppay.models import Shoppaydetail
import urllib.request as req
import urllib.parse as pa
from bs4 import BeautifulSoup as bs
import numpy as np
import pandas as pd
import logging
from django.utils.dateformat import DateFormat
from datetime import datetime, timedelta
from shopreview.models import Shopreview
from shopproduct.models import Shopproduct
import random
import requests

logger = logging.getLogger('shopmember')
# Create your views here.

# 메인페이지
class Index(View):
    def get(self,request):
        memid = request.session.get( "memid" )
        cartcount = Shopcart.objects.all().filter(user_id=memid).count()
        cartlist = Shopcart.objects.filter(user_id=memid)
        
        # 추천상품 (무작위)
        if memid : 
            rememberlog = open("log/shopproduct.log", 'r', encoding="utf-8")
            lines = rememberlog.readlines()[::-1]
            remembers=[]
            for line in reversed(lines):
                logs = line.split(":")
                user_id = logs[4].split(" ")[0]
                if user_id != memid:
                    continue
                else :
                    remembers.append(user_id)
                proditems=logs[9].split(" ")[0]
                if proditems not in remembers:
                    remembers.append(proditems)
                
                
                
            if memid not in remembers:
                items = list(Shopproduct.objects.all())
                random_id = random.sample(items, 10)
            else :
                items = list(Shopproduct.objects.filter(proditems=proditems))
            random_id = random.sample(items, 10)
            rememberlog.close()
        else :
            items = list(Shopproduct.objects.all())
            random_id = random.sample(items, 10)
        
        # 최근 본 상품
        productlog = open("log/shopproduct.log", 'r', encoding="utf-8")
        lines = productlog.readlines()[::-1]
        recents = []
        count = 0
        today = datetime.today()

        for line in lines:
            if count >= 4:
                break
            else:
                logs = line.split(" ")
                if datetime.strptime(logs[0][1:], "%Y-%m-%d") < today - timedelta(days=7):
                    break
                user_id = logs[5].split(":")[1]
                if user_id != memid:
                    continue
                prodnum = logs[6].split(":")[1]
                if prodnum not in recents:
                    recents.append(prodnum)
                    count += 1
        recentProducts = [Shopproduct.objects.get(prodnum=recent) for recent in recents]
        productlog.close()
        
        # rss
        url = "http://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp"
        values ={
            "stnId":109
            }
        params = pa.urlencode(values)
        url = url+"?"+params
        data = req.urlopen(url).read().decode("utf-8")
        
        # txt 파일 생성 저장
        with open("whether.txt", "w", encoding="utf-8") as f:
            f.write(data)
        
        readings= open("whether.txt","r",encoding="utf-8")
        
        lines = readings.readlines()[38]
        
        #기상예보 정규화
        relines= lines
        relines1= relines.strip()
        relines2= relines1.lstrip('<wf><![CDATA[○')
        relines3 = relines2.replace("○ " ,"")
        relines4 = relines3.replace("<br />○" ,"")
        relines5 = relines4.replace("<br />" ,"")
        relines6 = relines5.replace("<br /><br />*","")
        relines7 = relines6.rstrip("]]></wf>")
        relines8 = relines7.replace("   ","")
        relines9 = relines8.split(" (")
        relines10 = relines9[1]
        
        # ( 아웃터 )추천상품 (브랜드 무작위)
        # items = list(Shopproduct.objects.all().filter(proditems="아우터").filter(proditems="긴바지").filter(proditems="긴팔티"))
        items = list(Shopproduct.objects.raw("""
        select * from shopproduct_shopproduct 
        where proditems = '아우터' or proditems='긴바지' or proditems='긴팔티' or proditems='치마' or proditems='한벌옷' or proditems='신발'
        """))
        random_prod = np.random.choice(items, 10, replace=False)
        
        # sitems = list(Shopproduct.objects.all().filter(proditems="반팔티"))
        sitems = list(Shopproduct.objects.raw("""
        select * from shopproduct_shopproduct 
        where proditems = '반바지' or proditems='반팔티' or proditems='치마' or proditems='신발'
        """))
        srandom_prod = np.random.choice(sitems, 10,replace=False)
        
        # 많이산 상품
        # 구매 db에서 상품 번호들을 쿼리문 sum(prodcount)을 통해 합침
        # 가장 큰 숫자순으로 정렬 후 10개까지 표출
        countmax = Shopproduct.objects.raw("""
        select o.paydetailnum, o.prodnum, o.prodname, o.prodprice, sum(o.prodcount), o.prodmainimg, p.prodbrand, p.proditems
        from shoppay_shoppaydetail o inner join shopproduct_shopproduct p on(p.prodnum = o.prodnum)
        group by o.prodnum
        order by sum(prodcount) DESC LIMIT 10
        """)
        
        source = requests.get('https://www.weather.go.kr/weather/observation/currentweather.jsp')
        soup1 =bs(source.content,"html.parser")
        
        table = soup1.find('table',{'id':'weather_table'})
        data=[]
        
        for tr in table.find_all('tr') :
            tds=list(tr.find_all('td'))
            for td in tds:
                if td.find('a'):
                    point = td.find('a').get_text()
                    temp = tds[5].get_text()
                    humidity = tds[10].get_text()
                    data.append([point,temp,humidity])
                    
        
        with open('gweather.csv','w',encoding="utf-8") as f:
            f.write('지역,온도,습도\n')
            for i in data :
                f.write('{0},{1},{2}\n'.format(i[0],i[1],i[2]))
        
        df =pd.read_csv('gweather.csv', sep=",", encoding='utf-8')
        df.head()
        gion = df['온도']
        maxgion = max(gion) # 전국 최대온도
        # mingion = min(gion) # 전국 최저온도
        # meangion = round(np.mean(gion))
        
        
        # 실시간 검색어
        searchrank = pd.read_csv("search.csv", encoding='utf-8') # 저장한 csv 읽기
        searchrank.rename(columns={'하이힐':'title'}, inplace=True) # 칼럼이 '하이힐'로 먹음 변환해준것
        sl = searchrank.groupby('title')['title'].count().reset_index(name='count') # 그룹으로 묶은것들의 갯수를 샌다음 count라는 칼럼명을 지정해줌
        slh = sl.sort_values(by='count', ascending=False).head(10) # 위부터 10개만 뽑음
        slr = slh.reset_index(drop=True) # 기존의 index 테이블 삭제   
        
        # 장바구니
        totalprice = 0
        for pricesum in cartlist:
            totalprice += pricesum.prodnum.prodprice * pricesum.prodcount
         
        
        
        from sklearn.metrics.pairwise import cosine_similarity
        
        if memid :
            prodlog = open("log/shopreview.log", "r", encoding= "utf-8")
            prods = prodlog.readlines()
            data=[]
            for p in prods:
                logs = p.split(" ")
                user_id = logs[5].split(":")[1]
                prodnum = logs[6].split(":")[1]
                reviewrating = logs[8].split(":")[1]
                data.append([user_id,prodnum,reviewrating])
                
            with open("recomprod.csv","w",encoding="utf-8") as f:    
                f.write("user_id,prodnum,reviewrating\n")
                for i in data:
                    f.write("{0},{1},{2}\n".format(i[0],i[1],i[2]))
                    
            
            
            df = pd.read_csv("recomprod.csv", sep=",", encoding='utf-8')       
            df.head()
            # print()
            raticngs_matrix = df.pivot_table("reviewrating","user_id","prodnum")
            raticngs_matrix.fillna(0,inplace=True)
            
            raticngs_matrix_T= raticngs_matrix.T
            raticngs_matrix_T.head(3)
            
            # print(raticngs_matrix_T) #반전
            item_sim= cosine_similarity(raticngs_matrix_T,raticngs_matrix_T)
            
            item_sim_df= pd.DataFrame(item_sim, index=raticngs_matrix_T.index,columns=raticngs_matrix_T.index)
            # print(item_sim)#유사도
            # print()
            # print("유사도 데이터 프레임화\n",item_sim_df)#유사도 데이터프레임화
            
            rerere=item_sim_df[412].sort_values(ascending=False)[1:11]
            # print()
            # print("412번의 유사도 상품\n",rerere)
            # print(rerere.index[0])
            
            
            
            #영화추천( 최근접 이웃 협업 필터링)
            #함수
            def predict_rating(ratings_arr, item_sim_arr):
                # ratings_arr: u x i, item_sim_arr: i x i
                sum_sr = ratings_arr @ item_sim_arr
                sum_s_abs = np.array([np.abs(item_sim_arr).sum(axis=1)])
                ratings_pred =  sum_sr / sum_s_abs
                return ratings_pred
            
            ratings_pred = predict_rating(raticngs_matrix.values , item_sim_df.values)
            
            ratings_pred_matrix = pd.DataFrame(data=ratings_pred, index= raticngs_matrix.index,
                                               columns = raticngs_matrix.columns)
            ratings_pred_matrix.head(3)
            # print()
            # print(ratings_pred_matrix)
            
            # print("-" *70 ,"\n")
            # 별점이 있는 실제 영화만 추출(별점 없는건 빼고한다)
            #(하지만 지금 별점 데이터만 가지고 생성을 해서 이걸하는 의미가 없다 ) )
            from sklearn.metrics import mean_squared_error
            # 성능평가하는 MSE를 사용
            def get_mse(pred, actual):
                # 평점이 있는 실제 영화만 추출 (1차원 배열로 변환)
                pred = pred[actual.nonzero()].flatten()

shopmember/templates/confirm.html
	{% if result == 0 %}
	        <a style="color:green; font-weight: bold;">{{user_id}}는 사용할 수 있는</a> 아이디 입니다.
	{% else %}
	        <a style="color:red; font-weight: bold;">{{user_id}}는 사용할 수 없는</a> 아이디입니다.
	{% endif %}

shopmember/templates/delete.html
{% extends "base.html" %}

{% block title %}{% endblock %}
{% block header %} {% endblock %}

{% block contents %}
{% csrf_token %}
<script>
	// 자동으로 창이 닫히게 하는 함수
	function popupClose(form) {
		// target은 부모로 설정
		form.target = opener.name;
		form.submit();
		if(opener != null) {
			opener.userdeleteForm = null;
			self.close();
		}
	}
</script>
<header class="header navbar-area" style="position:absolute;">
        <section class="hero-area">
            <div class="container">
                <div class="col-12">
                    <div class="section-title">
                        <div class="main-menu-search" style="margin-left:200px;">
                            <form method="post" name="deleteform" action="delete" target="{% url 'member:mypage' %}" onsubmit="return deletecheck()">
                                <table>
                                    <tr>
                                        <div>
                                            <th><h3>비밀번호를 입력해 주세요<br><br></h3></th>
                                        </div>
                                    </tr>
                                    <tr>
                                        <th>
	                                        <div class="navbar-search search-style-5">
	                                            <div class="search-input">
	                                                <input type="password" placeholder="비밀번호" name="user_passwd" autofocus style="width:400px"><!-- name 추가 할것 -->
	                                                <br>
	                                                {% if message %}
	                                                	<span style="color:red">{{message}}</span>
	                                                {% endif %}
	                                            </div>
	                                        </div>
                                        </th>
                                    </tr>
                                    <tr>
                                        <td>
                                            <br>
                                            <div class="search-input" style="display:flex" style="width:1400px;">
                                                <input type="submit" value="탈퇴하기" style="background-color:lightblue" onclick="window.close()">
                                                <input type="button" value="취소" style="background-color:lightblue" onclick="window.close()">
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </header>
{% endblock %}

{% block footer %}
{% endblock %}

shopmember/templates/fitpap.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>pap_up</title>
</head>
<body>
    <img src="../static/images/dolphin.png" usemap="#pap" alt="event page">
    <map name="pap" id="pap">
        <area shape="rect" coords="380,457,487,492" href="#"
        alt="showpap" onclick="showpap();">
    </map>   
</body>
</html>

shopmember/templates/modify.html
{% extends "base.html" %}

{% block title %}{% endblock %}
{% block header %} {% endblock %}

{% block contents %}
{% csrf_token %}
<script>
	// 자동으로 창이 닫히게 하는 함수
	function popupClose(form) {
		// target은 부모로 설정
		form.target = opener.name;
		form.submit();
		if(opener != null) {
			opener.usermodifyForm = null;	
			self.close();
		}
	}
</script>
<header class="header navbar-area" style="position:absolute;">
        <section class="hero-area">
            <div class="container">
                <div class="col-12">
                    <div class="section-title">
                        <div class="main-menu-search" style="margin-left:200px;">
                            <form method="post" name="modifyform" action="modify" target="{% url 'member:mypage' %}">
                                <table>
                                    <tr>
                                        <div>
                                            <th><h3>비밀번호를 입력해 주세요<br><br></h3></th>
                                        </div>
                                    </tr>
                                    <tr>
                                        <th>
	                                        <div class="navbar-search search-style-5">
	                                            <div class="search-input">
	                                                <input type="password" placeholder="비밀번호" name="user_passwd" style="width:400px" autofocus><!-- name 추가 할것 -->
	                                                <br>
	                                                {% if message %}
	                                                	<span style="color:red">{{message}}</span>
	                                                {% endif %}
	                                            </div>
	                                        </div>
                                        </th>
                                    </tr>
                                    <tr>
                                        <td>
                                            <br>
                                            <div class="search-input" style="display:flex" style="width:1400px;">
                                                <input type="submit" value="수정하기" style="background-color:lightblue" onclick="window.close()">
                                                <input type="button" value="취소" style="background-color:lightblue" onclick="window.close()">
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </header>
{% endblock %}

{% block footer %}
{% endblock %}

shopmember/templates/mypage.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block locationbar %}{% endblock %}
{% block contents %}
<script>
		 function usermodifyForm() {
	window.name = "{% url 'member:mypage' %}";
	
	// window.open("자식창 이름", "자식창의 닉네임", "팝업창 옵션")
	window.open("{% url 'member:modify' %}", "usermodifyForm", "width=800, height=300, top=100, left=200, status=no,scrollbars=no, menubar=no"); 
	 }
</script>

<script>
		 function userdeleteForm() {
	window.name = "{% url 'member:mypage' %}";
	
	// window.open("자식창 이름", "자식창의 닉네임", "팝업창 옵션")
	window.open("{% url 'member:delete' %}", "userdeleteForm", "width=800, height=300, top=100, left=200, status=no,scrollbars=no, menubar=no"); 
	 }
</script>
<div>
<br>
    <header class="header navbar-area" style="z-index: 2;">
        <section class="hero-area">
            <div class="container" style="border: 1px solid lightgray; padding: 30px; border-radius: 8px; width: 1400px;">
                <div class="newsletter-form-head" style="font-size:30px;">
                    <span><a href="mypage.html">My Page</a></span>
                </div>
                <hr>
                <br>
                <div style="display:flex;">
                    <div style="background-color: lightgray; border-radius: 50%; width: 100px; height: 102px;">
                        <img src="{% static 'images\mypage.png' %}" style="width: 100px; height: 100px;  border-radius: 50%;">
                    </div>
                    <div style="padding-left:1%;">
                        <span style="font-size:40px">&nbsp;&nbsp;{{memberdto.user_name}}</span><span style="font-size:20px">님</span>
                    </div>

                    <div style="padding-left: 25%;">
                        <span style="font-size:40px">구매완료</span>
                        <div style="text-align: center;">
                            <span style="font-size:20px">{{paycount}}</span>
                        </div>
                    </div>

                    <div style="padding-left: 25%;">
                        <span style="font-size:40px">내 리뷰</span>
                        <div style="text-align: center;">
                            <span style="font-size:20px">{{reviewcount}}</span>
                        </div>
                    </div>
                </div>
                <hr>
                <div style="display:flex;">
                    <div style="width:20%; text-align: center;">
                        <div style="font-size: 20px;">
                            <span>내 정보 관리</span>
                        </div>
                        <div>
                            <ul>
                                <li>
                                    <a href="#" onclick="userdeleteForm()">회원 탈퇴</a>
                                </li>
                            </ul>
                            <ul>
                                <li>
                                    <a href="#" onclick="usermodifyForm()">회원 정보 수정</a>
                                </li>
                            </ul>
                            <ul>
                                <il>
                                	<a href="{% url 'qnaboard:myqna' %}">내가 작성한 qna</a>
                                </il>
                            </ul>
                            <hr>
                        </div>
                        <div style="font-size: 20px;">
                            <span>상품관련</span>
                        </div>
                        <div>
                            <ul>
                                <il>
                                	<a href="{% url 'prodcart:prodcart' %}">장바구니</a>
                                </il>
                            </ul>
                            <ul>
                                <il>
                                	<a href="{% url 'return:returnlist' %}">내 반품글</a>
                                </il>
                            </ul>
                            <ul>
                                <il>
                                	<a href="{% url 'member:myreview' %}">내 리뷰</a>
								</il>
                            </ul>
                            <hr>
                        </div>
                        
                        <div style="font-size: 20px;">
                        </div>
                        <div>
                        </div>
                    </div>
                    <div style="text-align: center;">
                        <div style="font-size:20px">
                            <span>내 구매 목록</span>
                        </div>
                        <hr>
                        <div style="padding:0%">
                            <table>
                                <colgroup>
                                    <col style="width: 100px;">
                                    <col style="width: 200px;">
                                    <col style="width: 400px;">
                                    <col style="width: 100px;">
                                    <col style="width: 100px;">
                                    <col style="width: 100px;">
                                    <col style="width: 195px;">
                                </colgroup>
                                <tbody>
                                    <!-- 이 쪽이 상품 출력부분 -->
                                    <div> 
                                        {% if paycount == 0 %}
                                           <tr>
                                              <td></td>
                                              <td></td>
                                              <td>구매 이력이 없습니다.</td>
                                              <td></td>
                                              <td></td>
                                              <td></td>
                                              <td></td>
                                           </tr>
                                        {% else %}
                                        
                                        {% for pay in paylist %}
                                        <tr>
                                        	<td>구매일자</td>
                                        	<td>{{pay.payreg_date|date:'Y.m.d'}}</td>
                                        	<td></td>
                                        	<td></td>
                                        	<td></td>
                                        	<td>배송상태</td>
                                        	<td>{{pay.delively_status}}</td>
                                        </tr>
                                        <tr>
                                        	<input type="hidden" value="{{pay.prodnum}}" name="prodnum">
                                            <td>{{pay.paydetailnum}}</td>
                                            <td><img src="/media/{{pay.prodmainimg}}"></td>
                                            <td><a href="../shopproduct/prodcontent?prodnum={{pay.prodnum}}">{{pay.prodname}}</a></td>
                                            <td>{{pay.prodoption}}</td>
                                            <td>{{pay.prodprice|intcomma}}원</td>
                                            <td>{{pay.prodcount}}개</td>
                                            <div class="search-input">
                                                <td style="flex-wrap:wrap;">
                                                	{% if pay.delively_status == "결제완료" %}
                                                	<input class="btn" type="button" value="주문 수정" style="width:200px; margin:5px; background-color:lightblue" onclick="location='../shoppay/ordermodify?paydetailnum={{pay.paydetailnum}}'">        		
                                                	{% elif pay.delively_status == "배송완료" %}
                                                	<input class="btn" type="button" value="리뷰 작성하러가기" style="width:200px; margin:5px; background-color:lightblue" onclick="location='../shopproduct/prodcontent?prodnum={{pay.prodnum}}'">
	                                                <input class="btn" type="button" value="반품/환불신청" style="border: 1px solid; margin:5px; width:200px; background-color:white"
	                                                   onclick="location='../shopreturn/returnwrite?paydetailnum={{pay.paydetailnum}}&prodnum={{pay.prodnum}}&prodname={{pay.prodname}}'">
	                                                {% elif pay.delively_status == "반품완료" %}
	                                                	<input class="btn" type="button" value="반품완료" style="border: 1px solid; margin:5px; width:200px; background-color:white">
                                                	{% else %}
	                                                    <input class="btn" type="button" value="상품이 배송중 입니다." style="border: 1px solid; margin:5px; width:200px; background-color:white">
	                                                    
                                                    {% endif %}
                                                </td>
                                            </div>
                                        </tr>
                                        {% endfor %}
                                        {% endif %}  
                                    </div>
                                    <!-- 여기 까지 -->
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <br><br><br>
        </section>
    </header>
</div>
{% endblock %}
<br>